theme = "gruvbox_dark_hard"

[editor]
line-number = 'relative'
mouse = false
bufferline = "always"
true-color = true
scrolloff = 8
color-modes = true
completion-timeout = 100
popup-border = "all"
rulers = [80,120]

[editor.cursor-shape]
insert = 'bar'
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode","version-control","file-modification-indicator"]
center = ["file-absolute-path","read-only-indicator"]
right = ["spinner", "diagnostics", "selections", "register", "position", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.file-picker]
hidden = false
parents = false
git-ignore = false

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]
n = ["search_next","align_view_center"]
N = ["search_prev","align_view_center"]
# C-u = ["half_page_up","align_view_center"]
# C-d = ["half_page_down","align_view_center"]

[keys.insert]
j = { k = "normal_mode" }

[keys.normal.space]
n = ":new" # create new buffer
x = ":bc" # close the current buffer
X = ":bc!" # force close the current buffer

[keys.normal.space.t]
# running test files
# g = ":pipe /Users/jmerten/.config/helix/scripts/gotest"
# g = ":sh go test -v ./..."

[keys.normal.space.i]
d = ":pipe date +'%a %b %d'"

