theme = "github_dark"

[editor]
line-number = 'relative'
mouse = false
bufferline = "multiple"
true-color = true
scrolloff = 8
color-modes = true

[editor.cursor-shape]
insert = 'bar'
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]
n = ["search_next","align_view_center"]
N = ["search_prev","align_view_center"]
# C-u = ["half_page_up","align_view_center"]
# C-d = ["half_page_down","align_view_center"]

[keys.insert]
j = { k = "normal_mode" } # exit insert mode

[keys.normal.space]
x = ":bc" # close current buffer
X = ":bc!" # force close current buffer

[keys.normal.space.t]
g = ":sh go test -v ./..."

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1
