local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})

vim.keymap.set("n","gd", builtin.lsp_definitions, {desc = "Goto Defintion"})
vim.keymap.set("n","gr", builtin.lsp_references, {desc = "Goto References"})
vim.keymap.set("n","gi", builtin.lsp_implementations, {desc = "Goto Implementations"})
vim.keymap.set("n", "<leader>D", builtin.lsp_type_definitions, { desc = "Goto Type Definition" })
vim.keymap.set("n", "<leader>ds", builtin.lsp_document_symbols, { desc = "Document Symbols" })
vim.keymap.set("n", "<leader>ws", builtin.lsp_dynamic_workspace_symbols, { desc = "Workspace Symbols" })
